sonar.projectKey=yuto-omi_web-task-front
sonar.organization=yuto-omi

sonar.sources=app,features,lib,components
sonar.tests=tests
sonar.exclusions=node_modules/**,.next/**,public/**,**/*.stories.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
